# Generated by Django 4.2 on 2024-02-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='mrp',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='minamount',
            new_name='offer_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='featured_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
