# Generated by Django 4.2 on 2024-02-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_amount_product_mrp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured_category',
            field=models.BooleanField(default=False),
        ),
    ]
