# Generated by Django 4.2 on 2024-02-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_featured_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
