# Generated by Django 5.0.2 on 2024-02-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('New Arrivals', 'New Arrivals'), ('Top Rated', 'Top Rated'), ('Featured', 'Featured')], max_length=25),
        ),
    ]
