# Generated by Django 5.0.2 on 2024-02-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mrp',
            new_name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
