# Generated by Django 4.2 on 2024-02-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_offer_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='pinterest',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
