# Generated by Django 4.2 on 2024-02-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_setting_pinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='logo/'),
        ),
    ]
