# Generated by Django 4.2 on 2024-02-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_setting_image_1_setting_image_2_setting_image_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='google_map',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
